# This workflow will apply the terraform scripts which would deploy the recquied infrastructure and the startup-sample-app

name: Terraform plan

on:
  
  pull_request:
    branches: 
        - main
        - dev
        - test    
env:
  TF_VERSION: 1.0.9
  environment: $GITHUB_BASE_REF
  organization: bcgov
  GIT_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
  SHA: ${{github.event.pull_request.head.sha}}
  Branch: ${GITHUB_HEAD_REF}
  
jobs:
  build:

    runs-on: ubuntu-latest       
    steps:
      - name: prod check 
        if: ${{ github.base_ref == 'main' }}
        run: echo "environment=prod" >> $GITHUB_ENV
    
    
      - name: checkout the repo and building the Backend    
        uses: actions/checkout@v2    
        
      
        
      - name: env name
        run: echo the will apply on ${{ env.environment }}
        
      - name: setting variables
        run: | 
             cd terraform/
             cat <<EOF > dev.auto.tfvars
             sha = "${{ env.SHA }}"
             git_url= "${{ env.GIT_URL }}"
             branch ="${{ env.Branch }}"
             
             EOF
             
    
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Planning startup-sample-project using terraform
        uses: hashicorp/setup-terraform@v1
      - run: |
            cd terraform/
            cat <<EOF > backend.hcl
            organization = "${{ env.organization }}"
            workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-ssp-vm" }
            EOF
            
            terraform init -backend-config=backend.hcl -input=false
            terraform plan -input=false
