# This workflow will run terraform destroy, which will destroy the infrstructure and the resourcespace instance, INCLUDING ALL DATA

name: terraform destroy

on:
  workflow_dispatch:
    inputs:
      env:
        description: select the environment to destroy
        type: environment
        required: true
      confirmation:
        description: 'Type the words "delete all data"'
        required: true

env:
  TF_VERSION: 1.14.3
  TERRAGRUNT_VERSION: 0.55.16
  environment: ${{ inputs.env }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: validate inputs
        run: |
          if [[ "${{ github.event.inputs.confirmation }}" != "delete all data" ]]; then
            echo '"delete all data" confirmation failed'
            exit 1
          fi

      - name: checkout the repository
        uses: actions/checkout@v4

      - name: print cloud_environment
        run: echo the cloud env is ${{ env.environment }}

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: install Terragrunt
        run: |
          curl -sSL -o /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64"
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1

      - name: destroying bcparks-dam using terragrunt
        run: |
          cd src/terraform/terragrunt/${{ env.environment }}
          terragrunt init -input=false
          terragrunt destroy -auto-approve -input=false
        env:
          licenceplate: ${{ vars.LICENCE_PLATE }}